=== anhnnpham/Metropolia-ISD-ECG/lib/adas1000/registers-0.1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
>
	<xs:simpleType name="number">
		<xs:annotation>
			<xs:documentation>C number literal</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="0b[01]+|0o[0-7]+|[0-9]+|0x[0-9A-Fa-f]+"></xs:pattern>
			<xs:minLength value="1"></xs:minLength>
			<xs:whiteSpace value="collapse"></xs:whiteSpace>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Documentable">
		<xs:sequence>
			<xs:element name="doc" minOccurs="0" maxOccurs="1" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Item">
		<xs:annotation>
			<xs:documentation>Nameable and documentable item</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="Documentable">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ItemWithBase">
		<xs:annotation>
			<xs:documentation>Item that can extend an other item</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="Item">
				<xs:attribute name="base" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="device">
		<xs:annotation>
			<xs:documentation>A device with registers</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Item">
					<xs:sequence>
						<xs:element name="register" minOccurs="1" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>Index addressed number storage location</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="ItemWithBase">
										<xs:sequence>
											<xs:element name="field" minOccurs="0" maxOccurs="unbounded">
												<xs:annotation>
													<xs:documentation>A set of bits in a register</xs:documentation>
												</xs:annotation>
												<xs:complexType>
													<xs:complexContent>
														<xs:extension base="ItemWithBase">
															<xs:sequence>
																<xs:element name="enum" minOccurs="0" maxOccurs="1">
																	<xs:annotation>
																		<xs:documentation>Defines possible values for a field</xs:documentation>
																	</xs:annotation>
																	<xs:complexType>
																		<xs:complexContent>
																			<xs:extension base="Documentable">
																				<xs:sequence>
																					<xs:element name="variant" minOccurs="0" maxOccurs="unbounded">
																						<xs:annotation>
																							<xs:documentation>Enum variant</xs:documentation>
																						</xs:annotation>
																						<xs:complexType>
																							<xs:complexContent>
																								<xs:extension base="Item">
																									<xs:attribute name="value" type="number" use="required" />
																								</xs:extension>
																							</xs:complexContent>
																						</xs:complexType>
																					</xs:element>
																				</xs:sequence>
																			</xs:extension>
																		</xs:complexContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="range" use="required">
																<xs:annotation>
																	<xs:documentation>Defines the bit range in the register</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="[0-9]+(:[0-9]+)?"></xs:pattern>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:extension>
													</xs:complexContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="address" type="number" use="required">
											<xs:annotation>
												<xs:documentation>Defines the address of a register</xs:documentation>
											</xs:annotation>
										</xs:attribute>
										<xs:attribute name="reset-value" type="number">
											<xs:annotation>
												<xs:documentation>Defines the reset value of a register</xs:documentation>
											</xs:annotation>
										</xs:attribute>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== anhnnpham/Metropolia-ISD-ECG/lib/adas1000/adas1000.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="adas1000.xsl"?>
<device
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="registers-0.1.xsd" name="ADAS1000"
>
	<register address="0x00" reset-value="0x000000" name="NOP">
		<doc>NOP (no operation)</doc>
	</register>
	<register address="0x01" reset-value="0x000000" name="ECGCTL">
		<doc>ECG control</doc>
		<field range="23" name="LAEN">
			<doc>ECG channel enable; shuts down power to the channel; the input becomes high-Z.</doc>
			<enum>
				<variant value="0" name="disabled">
					<doc>disables ECG channel. When disabled, the entire ECG channel is shut down and dissipating minimal power.</doc>
				</variant>
				<variant value="1" name="enabled">
					<doc>enables ECG channel.</doc>
				</variant>
			</enum>
		</field>
		<field range="22" name="LLEN" base="LAEN" />
		<field range="21" name="RAEN" base="LAEN" />
		<field range="20" name="V1EN" base="LAEN" />
		<field range="19" name="V2EN" base="LAEN" />
		<field range="10" name="CHCONFIG">
			<doc>Setting this bit selects the differential analog front end (AFE) input.</doc>
			<enum>
				<variant value="0" name="single-ended">
					<doc>single-ended input (digital lead mode or electrode mode).</doc>
				</variant>
				<variant value="1" name="differential">
					<doc>differential input (analog lead mode).</doc>
				</variant>
			</enum>
		</field>
		<field range="9:8" name="GAIN">
			<doc>Preamplifier and anti-aliasing filter overall gain.</doc>
			<enum>
				<variant value="0b00" name="x1.4">
					<doc>×1.4</doc>
				</variant>
				<variant value="0b01" name="x2.1">
					<doc>×2.1</doc>
				</variant>
				<variant value="0b10" name="x2.8">
					<doc>×2.8</doc>
				</variant>
				<variant value="0b11" name="x4.2">
					<doc>×1.4</doc>
				</variant>
			</enum>
		</field>
		<field range="7" name="VREFBUF">
			<doc>VREF buffer enable.</doc>
			<enum>
				<variant value="0" name="disabled">
					<doc>disabled</doc>
				</variant>
				<variant value="1" name="enabled">
					<doc>enabled (when using the internal VREF, VREFBUF must be enabled).</doc>
				</variant>
			</enum>
		</field>
		<field range="6" name="CLKEXT">
			<doc>
				Use external clock instead of crystal oscillator. When a device is configured as a master, the user can choose
				between an external crystal supplying the clock or an external clock source applied to the CLK_IO pin. The
				crystal oscillator is automatically disabled if configured as a slave in gang mode, and the slave device
				receives the clock from the master device. Note that the device powers up by default using an internal clock
				and switches to the appropriate clock (XTAL or CLK_IO) when configured on the first write to the CLKEXT bit.
			</doc>
			<enum>
				<variant value="0" name="XTAL">
					<doc>XTAL is clock source.</doc>
				</variant>
				<variant value="1" name="CLK_IO">
					<doc>CLK_IO is clock source.</doc>
				</variant>
			</enum>
		</field>
		<field range="5" name="Master">
			<doc>
				In gang mode, this bit selects the master (SYNC_GANG pin is configured as an output). When in single channel
				mode (gang = 0), this bit is ignored. ADAS1000-2 cannot be configured as a master device.
			</doc>
			<enum>
				<variant value="0" name="slave">
					<doc>0 (default) = slave.</doc>
				</variant>
				<variant value="1" name="master">
					<doc>1 = master.</doc>
				</variant>
			</enum>
		</field>
		<field range="4" name="Gang">
			<doc>Enable gang mode. Setting this bit causes CLK_IO and SYNC_GANG to be activated.</doc>
			<enum>
				<variant name="single channel mode" value="0" />
				<variant name="gang mode" value="1" />
			</enum>
		</field>
		<field range="3" name="HP">
			<doc>
				Selects the noise/power performance. This bit controls the ADC sampling
				frequency. See the Specifications section for further details. This bit
				also affects the respiration carrier frequency as discussed in the
				Respiration Carrier Frequency section.
			</doc>
			<enum>
				<variant value="0" name="1 MSPS, low power" />
				<variant value="1" name="2 MSPS, high performance/low noise" />
			</enum>
		</field>
		<field range="2" name="CNVEN">
			<doc>
				Conversion enable. Setting this bit enables the ADC conversion and
				filters.
			</doc>
			<enum>
				<variant value="0" name="idle" />
				<variant value="1" name="conversion enable" />
			</enum>
		</field>
		<field range="1" name="PWREN">
			<doc>
				Power enable. Clearing this bit powers down the device. All analog
				blocks are powered down and the external crystal is disabled. The
				register contents are retained during power down as long as DVDD is
				not removed.
			</doc>
			<enum>
				<variant value="0" name="power down" />
				<variant value="1" name="power enable" />
			</enum>
		</field>
		<field range="1" name="SWRST">
			<doc>
				Software reset. Setting this bit clears all registers to their reset
				value. This bit automatically clears itself. The software reset requires
				a NOP command to complete the reset.
			</doc>
			<enum>
				<variant value="0" name="NOP" />
				<variant value="1" name="reset" />
			</enum>
		</field>
	</register>
	<register address="0x02" reset-value="0x000000" name="LOFFCTL">
		<doc>Lead-off control</doc>
	</register>
	<register address="0x03" reset-value="0x000000" name="RESPCTL">
		<doc>Respiration control</doc>
	</register>
	<register address="0x04" reset-value="0x000F88" name="PACECTL">
		<doc>Pace detection control</doc>
	</register>
	<register address="0x05" reset-value="0xE00000" name="CMREFCTL">
		<doc>Common-mode, reference, and shield drive control</doc>
		<field range="23" name="LACM">
			<enum>
				<variant value="0" name="no" />
				<variant value="1" name="yes" />
			</enum>
		</field>
		<field range="22" name="LLCM" base="LACM" />
		<field range="21" name="RACM" base="LACM" />
		<field range="20" name="V1CM" base="LACM" />
		<field range="19" name="V2CM" base="LACM" />

		<field range="14" name="LARLD">
			<enum>
				<variant value="0" name="no" />
				<variant value="1" name="yes" />
			</enum>
		</field>
		<field range="13" name="LLRLD" base="LARLD" />
		<field range="12" name="RARLD" base="LARLD" />
		<field range="11" name="V1RLD" base="LARLD" />
		<field range="10" name="V2RLD" base="LARLD" />
		<field range="9"  name="CERLD" base="LARLD" />

		<field range="8"  name="CEREFEN">
			<doc>Common electrode (CE) reference.</doc>
			<enum>
				<variant value="0" name="disabled" />
				<variant value="1" name="enabled" />
			</enum>
		</field>

		<field range="7:4" name="RLDSEL">
			<doc>Select electrode for reference drive.</doc>
			<enum>
				<variant value="0" name="RLD_OUT" />
				<variant value="1" name="LA" />
				<variant value="2" name="LL" />
				<variant value="3" name="RA" />
				<variant value="4" name="V1" />
				<variant value="5" name="V2" />
			</enum>
		</field>

		<field range="3" name="DRVCM">
			<doc>
				Common-mode output. When set, the internally derived common-mode signal
				is driven out of the common-mode pin. This bit has no effect if an
				external common mode is selected.
			</doc>
			<enum>
				<variant value="0" name="not driven" />
				<variant value="1" name="driven" />
			</enum>
		</field>

		<field range="2" name="EXTCM">
			<doc>
				Select the source of common mode (use when operating multiple devices
				together).
			</doc>
			<enum>
				<variant value="0" name="internal" />
				<variant value="1" name="external" />
			</enum>
		</field>

		<field range="1" name="RLDEN">
			<doc>Enable right leg drive reference electrode.</doc>
			<enum>
				<variant value="0" name="disabled" />
				<variant value="1" name="enabled" />
			</enum>
		</field>

		<field range="0" name="SHDLEN">
			<doc>Enable shield drive.</doc>
			<enum>
				<variant value="0" name="disabled" />
				<variant value="1" name="enabled" />
			</enum>
		</field>
	</register>
	<register address="0x06" reset-value="0x000000" name="GPIOCTL">
		<doc>GPIO control</doc>
	</register>
	<register address="0x07" reset-value="0x242424" name="PACEAMPTH">
		<doc>Pace amplitude threshold</doc>
	</register>
	<register address="0x08" reset-value="0x000000" name="TESTTONE">
		<doc>Test tone</doc>
	</register>
	<register address="0x09" reset-value="0x002000" name="CALDAC">
		<doc>Calibration DAC</doc>
	</register>
	<register address="0x0A" reset-value="0x079000" name="FRMCTL">
		<doc>Frame control</doc>
		<field range="23" name="LEAD1_LADIS">
			<doc>
				Include/exclude word from ECG data frame. If the electrode/lead is
				included in the data-word and the electrode falls off, the data-word is
				undefined.
			</doc>
			<enum>
				<variant value="0" name="include" />
				<variant value="1" name="exclude" />
			</enum>
		</field>
		<field range="22" name="LEAD2_LLDIS" base="LEAD1_LADIS" />
		<field range="21" name="LEAD3_RADIS" base="LEAD1_LADIS" />
		<field range="20" name="V1DIS" base="LEAD1_LADIS" />
		<field range="19" name="V2DIS" base="LEAD1_LADIS" />
		<field range="14" name="PACEDIS" base="LEAD1_LADIS" />
		<field range="13" name="RESPMDIS" base="LEAD1_LADIS" />
		<field range="12" name="RESPPHDIS" base="LEAD1_LADIS" />
		<field range="11" name="LOFFDIS" base="LEAD1_LADIS" />
		<field range="10" name="GPIODIS" base="LEAD1_LADIS" />
		<field range="9" name="CRCDIS" base="LEAD1_LADIS" />
		<field range="7" name="ADIS">
			<doc>
				Automatically excludes PACEDIS[14], RESPMDIS[13], LOFFDIS[11] words if
				their flags are not set in the header.
			</doc>
			<enum>
				<variant value="0" name="fixed frame format" />
				<variant value="1" name="autodisable words" />
			</enum>
		</field>
		<field range="6" name="RDYRPT">
			<doc>
				Ready repeat. If this bit is set and the frame header indicates data is
				not ready, the frame header is continuously sent until data is ready.
			</doc>
			<enum>
				<variant value="0" name="always send entire frame" />
